// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var Dngconfig;

  angular.module("dng.parse").service("Dngconfig", Dngconfig = function() {
    var configs;
    configs = {};
    return configs;
  });

}).call(this);

/*
//@ sourceMappingURL=dngconfig.map
*/
