// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var controller, html;

  html = "<a style=\"cursor: pointer\" ng-click=\"signout()\">\n  <i class=\"icon-off\"></i>\n  Sign out\n</a>";

  controller = function(root, scope) {
    return scope.signout = function() {
      Parse.User.logOut();
      delete root.user;
      return root.go('/');
    };
  };

  angular.module('dng.parse').directive('logout', function() {
    return {
      template: html,
      replace: true,
      restrict: 'E',
      scope: true,
      controller: ['$rootScope', '$scope', controller]
    };
  });

}).call(this);

/*
//@ sourceMappingURL=logout.map
*/
