// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('dng.parse').directive('logout', function() {
    return {
      template: '<div></div>',
      restrict: 'E',
      link: function(scope, element, attrs) {
        return element.text('this is the logout directive');
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=logout.map
*/
